services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:1.17.0
    container_name: cloudflare-ddns
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      DOMAINS: jrwroberts.co.uk
      PROXIED: "true"
      IP6_PROVIDER: none
