site_name: James Engineering Training Platform

theme:
  name: material

nav:
  - Home: index.md
  - Projects: projects.md
  - Architecture: architecture.md
  - Training:
      - Linux:
          - Overview: courses/linux/content/course-index.md

      - Kubernetes:
          - Overview: courses/kubernetes/content/index.md

      - Cloud:
          - Overview: courses/cloud/content/index.md

      - Azure:
          - Overview: courses/azure/content/index.md

      - Docker:
          - Overview: courses/docker/index.md

      - Git:
          - Overview: courses/git/index.md

      - Monitoring:
          - Overview: courses/monitoring/index.md

      - Security:
          - Overview: courses/security/index.md

      - Microsoft 365:
          - Overview: courses/microsoft365/index.md
