services:

  nginx:
    image: nginx:latest
    container_name: cloud-platform-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx:/etc/nginx/conf.d

    networks:
      - cloud-platform


networks:

  cloud-platform:
    external: true

