services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/james/homelab/portainer/data:/data
    restart: unless-stopped
    networks:
      - apps
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - CAP_HOST_MANAGEMENT=1
    networks:
      - apps
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
#    ports:
#      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - apps
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
#    ports:
#      - "8081:80"
    volumes:
      - /home/james/docker/data:/srv
      - /home/james/docker/data/management/filebrowser/config:/config
      - /home/james/docker/data/management/filebrowser/database:/database
    restart: unless-stopped
    networks:
      - apps
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --cleanup
      --label-enable
      --schedule "0 0 6 * * *"
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=jrwroberts1976@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=jrwroberts1976@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=jrwroberts1976@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=adzn pklz mqqu abfj
    networks:
      - apps
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


networks:
  apps:
    external: true
    name: homelab_apps
