services:

  portainer:
    image: portainer/portainer-ce:2.44.0
    container_name: portainer
    ports:
      - "192.168.2.220:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/james/homelab/portainer/data:/data
    restart: unless-stopped
    networks:
      - apps


  portainer_agent:
    image: portainer/agent:2.44.0
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - "192.168.2.220:9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - CAP_HOST_MANAGEMENT=1
    networks:
      - apps


  dozzle:
    image: ${DOZZLE_IMAGE:-amir20/dozzle:v10.7.2}
    container_name: dozzle
#    ports:
#      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - apps
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"


  filebrowser:
    image: ${FILEBROWSER_IMAGE:-filebrowser/filebrowser:v2.63.23}
    container_name: filebrowser
#    ports:
#      - "8081:80"
    volumes:
      - /home/james/docker/data:/srv
      - /home/james/docker/data/management/filebrowser/config:/config
      - /home/james/docker/data/management/filebrowser/database:/database
    restart: unless-stopped
    networks:
      - apps
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"



networks:
  apps:
    external: true
    name: homelab_apps
