services:

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped

    volumes:
      - /opt/cloud-platform/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    ports:
      - "9090:9090"

    networks:
      - cloud-platform


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped

    volumes:
      - grafana-data:/var/lib/grafana

    ports:
      - "3000:3000"

    networks:
      - cloud-platform


  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped

    ports:
      - "9100:9100"

    networks:
      - cloud-platform


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

    ports:
      - "8080:8080"

    networks:
      - cloud-platform


volumes:

  prometheus-data:
  grafana-data:


networks:

  cloud-platform:
    external: true
