---

- name: Install certbot packages
  become: true
  dnf:
    name:
      - certbot
      - python3-certbot-nginx
    state: present


- name: Create certbot webroot directory
  become: true
  file:
    path: /var/www/certbot
    state: directory
    mode: '0755'

- name: Create Certbot challenge directory
  ansible.builtin.file:
    path: /var/www/certbot/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: "0755"


- name: Obtain Let's Encrypt certificate
  become: true
  command: >
    certbot certonly
    --webroot
    -w /var/www/certbot
    -d {{ grafana_domain }}
    -d {{ prometheus_domain }}
    -d {{ rosie_domain }}
    --non-interactive
    --agree-tos
    -m {{ letsencrypt_email }}
  args:
    creates: /etc/letsencrypt/live/{{ grafana_domain }}/fullchain.pem

- name: Deploy certbot renewal service
  become: true
  template:
    src: certbot-renew.service.j2
    dest: /etc/systemd/system/certbot-renew.service


- name: Deploy certbot renewal timer
  become: true
  template:
    src: certbot-renew.timer.j2
    dest: /etc/systemd/system/certbot-renew.timer


- name: Enable certbot renewal timer
  become: true
  systemd:
    daemon_reload: true
    name: certbot-renew.timer
    enabled: true
    state: started

