services:

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.15.0
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "192.168.2.220:81:81"
      - "443:443"
    volumes:
      - /home/james/docker/data/proxy-auth/npm/data:/data
      - /home/james/docker/data/proxy-auth/npm/letsencrypt:/etc/letsencrypt
    networks:
      - apps


  authelia:
    image: "${AUTHELIA_IMAGE:-authelia/authelia@sha256:1b363e9279e742397966333f364e0876ae02bf5c876de73e83af6d48c57ff51b}"
    container_name: authelia
    restart: unless-stopped
    ports:
      - "192.168.2.220:9091:9091"
    volumes:
      - /home/james/docker/data/proxy-auth/authelia/config:/config
    environment:
      - TZ=Europe/London
    networks:
      - apps


  duckdns:
    image: lscr.io/linuxserver/duckdns:af6dcae5-ls86
    container_name: duckdns
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBDOMAINS=jrwroberts
      - FILE__TOKEN=/run/secrets/duckdns_token
      - UPDATE_IP=ipv4
    secrets:
      - duckdns_token
    networks:
      - apps
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"


networks:
  apps:
    external: true
    name: homelab_apps

secrets:
  duckdns_token:
    file: /home/james/docker/secrets/duckdns-token
