server {

    listen 80;

    server_name prometheus.jrwroberts.co.uk;

    location / {

        proxy_pass http://prometheus:9090;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

    }
}
